version: '3'

services:
  chatapi:
    build: .
    volumes:
      - ./:/src/app
    ports:
      - 4000:4000
    command: npm start
    
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
